### PR TITLE
Rename demo app from app to demo-app

### LINKED ISSUE #77: Rename the demo app from `app` to `demo-app`
Screenshot 2024-03-19 at 15 37 25

### PR DESCRIPTION
**Pull request by eyedol**
Closes #77

### Description

Renamed the `app` module to `demo-app` as required by issue #77

Before | After
:--: | :--:
Before screenshot indicating demo app module as app | After screenshot indicating demo app module as demo-app

### Testing Steps

NA

**Note:** I did not find any [`good first issue`](https://github.com/Automattic/Gravatar-SDK-Android/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) to work on so picked this one as it seems trivial as a `good first issue` to work on 😃

### CODE REVIEW

**Comment by mlumeau** [comment]
Hi Henry, thank you for your interest in this project. 
Our demo app module is only here for end-to-end testing of the SDK features. We do not aim at publishing it as a stand-alone app, so ~~I don't see a need to rename this module. I'm closing this PR.~~
Edit: just saw the ticket, my bad.

**Comment by hamorillo** [comment]
Hey @eyedol! Thanks for your contribution and interest in the Gravatar SDK. Sorry for the delay in reviewing your PR. 

We've merged some code, and now there are some conflicts. Could you please solve them? After that, we'll run CI checks for your PR, and if everything looks good, we'll merge it.

**Comment by eyedol** [comment]
> Hey @eyedol! Thanks for your contribution and interest in the Gravatar SDK. Sorry for the delay in reviewing your PR.
> 
> We've merged some code, and now there are some conflicts. Could you please solve them? After that, we'll run CI checks for your PR, and if everything looks good, we'll merge it.

Sure. On it...

**Comment by eyedol** [comment]
> > Hey @eyedol! Thanks for your contribution and interest in the Gravatar SDK. Sorry for the delay in reviewing your PR.
> > We've merged some code, and now there are some conflicts. Could you please solve them? After that, we'll run CI checks for your PR, and if everything looks good, we'll merge it.
> 
> Sure. On it...

@hamorillo thanks for the review earlier. And no worries with the late response. I have fixed the merge conflict and waiting on CI to finish. Hopefully it's all green otherwise I'll look into anything that will require my attention.

**Review by hamorillo — APPROVED** [review]
Everything looks good @eyedol :shipit: 

Thanks again for your contribution.

**Pull request merged**
